api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'

    formats:
        json:     ['application/json']
        html:     ['text/html']
